Repository ObiekweAgbu/Enterprise-Systems-Development, pull requests merged in 2020-12, with the labels that each got.

#11 User Class Model
  SmartCare CW/UsersClass.asta
Labels: documentation

#14 Initial Burn Down Chart
  SmartCare CW/Burn_Down_Chart.xlsx
Labels: documentation

#30 database
  SmartCare CW/SmartCare.sql
  SmartCare CW/Sprint Gannt ESD.xlsx
Labels: enhancement

#33 Gantt chart
  SmartCare CW/Sprint Gannt ESD.xlsx
Labels: documentation

#34 Task Delivery form for sprint 1
  SmartCare CW/Task Delivery Form.docx
Labels: documentation

#39 Updated burndown chart for sprint 2 and separate image files
  SmartCare CW/Bundownchart-sprint2.png
  SmartCare CW/Burn_Down_Chart_.xlsx
  SmartCare CW/burndownchart-sprint1.png
Labels: documentation

#44 updated burndown chart without charts sprint 2
  SmartCare CW/Updated_Burn_Down_Chart_sprint 2.xlsx
Labels: documentation

#50 Developing loginController and loginData and initial viewer dashboard for Doctors, nurses, admin, client, updated database
  .gitignore
  SmartCare CW/SmartCare.sql
  SmartCare CW/SmartCare1.sql
  SmartCare CW/SmartCareApp/build/generated/classes/org/apache/jsp/Login_jsp.class
  SmartCare CW/SmartCareApp/build/generated/src/org/apache/jsp/Login_jsp.class.smap
  SmartCare CW/SmartCareApp/build/generated/src/org/apache/jsp/Login_jsp.java
  SmartCare CW/SmartCareApp/build/web/Doctor_DB.jsp
  SmartCare CW/SmartCareApp/build/web/Login.jsp
  SmartCare CW/SmartCareApp/build/web/Nurse_DB.jsp
  SmartCare CW/SmartCareApp/build/web/WEB-INF/classes/.netbeans_automatic_build
  SmartCare CW/SmartCareApp/build/web/WEB-INF/classes/.netbeans_update_resources
  SmartCare CW/SmartCareApp/build/web/WEB-INF/classes/Login/LoginController.class
  SmartCare CW/SmartCareApp/build/web/WEB-INF/classes/Login/LoginData.class
  SmartCare CW/SmartCareApp/build/web/WEB-INF/lib/derby-10.15.2.0.jar
  SmartCare CW/SmartCareApp/build/web/WEB-INF/lib/derbyshared-10.15.2.0.jar
  SmartCare CW/SmartCareApp/build/web/WEB-INF/lib/derbytools.jar
  SmartCare CW/SmartCareApp/build/web/WEB-INF/web.xml
  SmartCare CW/SmartCareApp/build/web/admin.jsp
  SmartCare CW/SmartCareApp/build/web/client_DB.jsp
  SmartCare CW/SmartCareApp/build/web/redirect.jsp
  SmartCare CW/SmartCareApp/nbproject/build-impl.xml
  SmartCare CW/SmartCareApp/nbproject/genfiles.properties
  SmartCare CW/SmartCareApp/nbproject/project.properties
  SmartCare CW/SmartCareApp/nbproject/project.xml
  SmartCare CW/SmartCareApp/src/java/Account.java
  SmartCare CW/SmartCareApp/src/java/Login/LoginController.java
  SmartCare CW/SmartCareApp/src/java/Login/LoginData.java
  SmartCare CW/SmartCareApp/web/Doctor_DB.jsp
  SmartCare CW/SmartCareApp/web/Login.jsp
  SmartCare CW/SmartCareApp/web/Nurse_DB.jsp
  SmartCare CW/SmartCareApp/web/admin.jsp
  SmartCare CW/SmartCareApp/web/client_DB.jsp
  SmartCare CW/SmartCareApp/web/redirect.jsp
Labels: bug, enhancement

#52 Task delivery form sprint 2
  SmartCare CW/Task Delivery Form Sprint 2.docx
Labels: documentation
